// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbcV6AQxQOfZgaeg0l3bhbN3kwF_ccqCM',
    appId: '1:310434481826:web:aa845fa76c416faf0879fb',
    messagingSenderId: '310434481826',
    projectId: 'webgro-7929c',
    authDomain: 'webgro-7929c.firebaseapp.com',
    storageBucket: 'webgro-7929c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn7Pk9FkeTFyP0-HHb4O5Vi4sFEmTDQfE',
    appId: '1:310434481826:android:f2192faf9811c3300879fb',
    messagingSenderId: '310434481826',
    projectId: 'webgro-7929c',
    storageBucket: 'webgro-7929c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBROS9MT1m73A5SyOcogAZWW6H2Fkv6tl4',
    appId: '1:310434481826:ios:02e64525a390edc30879fb',
    messagingSenderId: '310434481826',
    projectId: 'webgro-7929c',
    storageBucket: 'webgro-7929c.firebasestorage.app',
    iosBundleId: 'com.example.financeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBROS9MT1m73A5SyOcogAZWW6H2Fkv6tl4',
    appId: '1:310434481826:ios:02e64525a390edc30879fb',
    messagingSenderId: '310434481826',
    projectId: 'webgro-7929c',
    storageBucket: 'webgro-7929c.firebasestorage.app',
    iosBundleId: 'com.example.financeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbcV6AQxQOfZgaeg0l3bhbN3kwF_ccqCM',
    appId: '1:310434481826:web:76589d433887ae010879fb',
    messagingSenderId: '310434481826',
    projectId: 'webgro-7929c',
    authDomain: 'webgro-7929c.firebaseapp.com',
    storageBucket: 'webgro-7929c.firebasestorage.app',
  );
}
